name: Build Template

on:
  workflow_call:
    inputs:
      template:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-success: ${{ steps.build-result.outputs.success }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Initialize Nix Flake
        run: |
          mkdir -p my-config && cd my-config
          nix flake --extra-experimental-features 'nix-command flakes' init -t github:dustinlyons/nixos-config#${{ inputs.template }}

      - name: Apply CI User Info
        run: |
          cd /home/runner/work/nixos-config/nixos-config/my-config
          /home/runner/work/nixos-config/nixos-config/bin/apply-ci

      - name: Build Nix Flake
        run: |
          cd /home/runner/work/nixos-config/nixos-config/my-config
          git add .
          echo "Building Flake..."
          if nix build --extra-experimental-features 'nix-command flakes' /home/runner/work/nixos-config/nixos-config/my-config#nixosConfigurations."${{ inputs.arch }}".config.system.build.toplevel; then
            echo "success=true" >> $GITHUB_ENV
          else
            echo "Build failed, listing flake.lock for debugging:"
            cat flake.lock
            echo "success=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Determine build result
        id: build-result
        run: echo "success=${{ env.success }}" >> $GITHUB_OUTPUT

